#!/bin/bash
sudo apt update
sudo apt install openjdk-8-jre apt-transport-https wget nginx
wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add
cat "deb https://artifacts.elastic.co/packages/6.x/apt stable main" > /etc/apt/sources.list.d/elastic.list
#TODO push kibana config
sudo apt update
sudo apt install elasticsearch kibana
echo "type the following to create password replace yourpassword with a password: echo 'admin:`openssl passwd -apr1 YourPassword`' | sudo tee -a /etc/nginx/htpasswd.kibana"
#TODO push nginx config
sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/kibana /etc/nginx/sites-enabled/kibana
sudo systemctl restart nginx
sudo apt install logstash
curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-6.5.4-amd64.deb
sudo dpkg -i filebeat-6.5.4-amd64.deb
#TODO push filebeat config
