#!/bin/bash
sudo apt update
sudo apt install openjdk-8-jre apt-transport-https wget nginx
wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add
echo "deb https://artifacts.elastic.co/packages/6.x/apt stable main" > /etc/apt/sources.list.d/elastic.list
sudo apt update
sudo apt install elasticsearch kibana
cp kibana.yml /etc/kibana/kibana.yml
cp nginx-kibana-config /etc/nginx/sites-available/kibana
sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/kibana /etc/nginx/sites-enabled/kibana
sudo systemctl restart nginx
#sudo apt install logstash
#curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-6.5.4-amd64.deb
#sudo dpkg -i filebeat-6.5.4-amd64.deb
#TODO push filebeat config
